### ISSUE TITLE
Update actions/github-script dependency

### ISSUE THREAD

**Issue by jeremycopinlm** [ChristopherHX/conditional#3]
Hello

It's about Github Actions warning :

_Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/github-script@v4_

Could you update your action please ? Thanks

**Comment by ChristopherHX** [comment]
No problem, you might have to change the sha of the action to `a675ed4b9377f0f6e385f1c992f4a53de60ec521` in your workflow file

**Comment by jeremycopinlm** [comment]
many thanks =)
